#!/bin/bash

echo "Converting SVG files into PNG, EPS, PDF and AI files"
for SVG in *.svg; do
  echo "Exporting $SVG into PNG"
  inkscape "$SVG" --export-png="$SVG.png" --export-area-drawing --export-area-snap

  echo "Exporting $SVG into PNG at 180dpi"
  inkscape "$SVG" --export-png="$SVG-x2.png" --export-area-drawing --export-area-snap --export-dpi=180

  echo "Exporting $SVG into EPS"
  inkscape "$SVG" --export-eps="$SVG.eps"

  echo "Exporting $SVG into PDF"
  inkscape "$SVG" --export-pdf="$SVG.pdf"

  echo "Exporting $SVG into AI"
  uniconvertor "$SVG" "$SVG.ai"

done

echo "Renaming files"
  rename 's/\.svg//' *.png
  rename 's/-x2/_x2/' *.png
  rename 's/\.svg//' *.eps
  rename 's/\.svg//' *.pdf
  rename 's/\.svg//' *.ai

echo "Moving files"
  mkdir ai
  mv *.ai ai/

  mkdir eps
  mv *.eps eps/

  mkdir pdf
  mv *.pdf pdf/

  mkdir png-x2
  mv *_x2.png png-x2/

  mkdir png
  mv *.png png/

exit 0
